### PR TITLE
Make miscellaneous fixes for Clippy warnings

### PR DESCRIPTION
**Pull request by ArniDagur**
I didn't fix _all_ of the clippy warnings, as some of them are non-trivial.

### CODE REVIEW

**Comment by Luminarys** [comment]
Looks like there's a compilation error in Travis, could you fix it?

Also, what's the minimum version of rust that can build these changes? I don't mind bumping up the minimum, but I'd prefer if the minimum remains a few months behind stable at the least.

**Comment by ArniDagur** [comment]
The minimum Rust version should be the same, as it compiles with `1.30.0-x86_64-unknown-linux-gnu`.

**Comment by Luminarys** [comment]
Looks good, thanks!
